/* Speech, display, calculator evaluation, dynamic boards, and tab navigation. */
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js', { updateViaCache: 'none' }).then(registration => registration.update()).catch(() => {});
const display=document.querySelector('#display');const status=document.querySelector('#status');const speech=window.speechSynthesis;let voices=[];let lastResult='';
const phrases=['I need help','I have a question',"I'm ready", "I don't understand",'Can you repeat that?','I need more time','Thank you'];
const sets={algebra:[['x','x'],['y','y'],['a','a'],['b','b'],['=',' = '],['≠',' != '],['<',' < '],['>',' > '],['^','**'],['|x|','abs(']],calculus:[['Integral','']],greek:[['α','α'],['β','β'],['γ','γ'],['δ','δ'],['θ','θ'],['λ','λ'],['μ','μ'],['σ','σ'],['φ','φ'],['ω','ω'],['∧','∧'],['∨','∨'],['∩','∩'],['∪','∪'],['→','→'],['∀','∀'],['∃','∃'],['∈','∈']],functions:[['sin','sin('],['cos','cos('],['tan','tan('],['√','sqrt('],['ln','log('],['log₁₀','log10('],['eˣ','exp('],['!','factorial('],['⌈x⌉','ceil('],['⌊x⌋','floor('],['|x|','abs('],['sin⁻¹','asin('],['cos⁻¹','acos('],['tan⁻¹','atan(']],words:[['I','I'],['need','need'],['want','want'],['like','like'],['feel','feel'],['more','more'],['less','less'],['to','to'],['go','go'],['stop','stop'],['because','because'],['today','today']]};
function setStatus(message){status.textContent=message}function append(value,space=false){if(!space&&window.insertFunctionValue?.(value))return;const start=display.selectionStart??display.value.length;const end=display.selectionEnd??start;display.setRangeText((space&&start&&display.value[start-1]!==' '?' ':'')+value,start,end,'end');display.focus();window.scheduleCalculatorPreview?.()}function speak(text=display.value){if(!text.trim())return;const utterance=new SpeechSynthesisUtterance(text);const selected=document.querySelector('#voice-select').value;const voice=voices.find(item=>item.name===selected);if(voice)utterance.voice=voice;utterance.rate=Number(document.querySelector('#rate-range').value)/175;utterance.volume=Number(document.querySelector('#volume-range').value)/100;speech.cancel();speech.speak(utterance);setStatus('Speaking current display.')}
function makeButtons(){const quick=document.querySelector('#quick-phrases');phrases.forEach(text=>{const button=document.createElement('button');button.className='button';button.textContent=text;button.onclick=()=>{display.value=text;if(document.querySelector('#auto-speak')?.checked!==false)window.speak(text);else setStatus('Phrase selected. Press Speak to read it aloud.')};quick.append(button)});document.querySelectorAll('[data-buttons]').forEach(container=>{sets[container.dataset.buttons].forEach(([label,value])=>{const button=document.createElement('button');button.className='button';button.textContent=label;button.onclick=()=>{if(container.dataset.buttons==='calculus')window.openIntegral();else append(value,container.dataset.buttons==='words')};container.append(button)})})}

function loadVoices(){voices=speech?.getVoices()||[];const select=document.querySelector('#voice-select');let previous=select.value;try{previous=previous||JSON.parse(localStorage.getItem('math-aac-settings')||'{}')?.['voice-select'];}catch(_){}select.innerHTML='';voices.forEach(voice=>{const option=document.createElement('option');option.value=voice.name;option.textContent=voice.name;select.append(option)});const preferred=voices.find(v=>/zira|aria|jenny|samantha|hazel/i.test(v.name));if(voices.some(v=>v.name===previous))select.value=previous;else if(preferred)select.value=preferred.name}function selectTab(tab){document.querySelectorAll('.main-tabs .tab').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));document.querySelectorAll('.subject').forEach(section=>section.classList.toggle('active',section.id===tab))}function selectSubtab(button){const parent=button.closest('.subject');parent.querySelectorAll('.subtab').forEach(item=>item.classList.toggle('active',item===button));const target=button.dataset.subtab;parent.querySelectorAll('.subpanel').forEach(panel=>panel.classList.toggle('active',panel.id===target))}
document.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.tab){selectTab(target.dataset.tab);return}if(target.dataset.subtab){selectSubtab(target);return}if(target.dataset.value){append(target.dataset.value);return}const action=target.dataset.action;if(action==='speak')window.speak();if(action==='backspace'&&!window.backspaceMath?.()){const end=display.selectionEnd??display.value.length;const start=display.selectionStart??end;display.setRangeText('',start===end?Math.max(0,start-1):start,end,'end');display.focus();}if(action==='clear'){display.value='';window.scheduleCalculatorPreview?.();}if(action==='integral')window.openIntegral();if(action==='evaluate')window.evaluate();if(action==='mode')window.toggleCalculatorMode();if(action==='sign')window.toggleCalculatorSign();if(action==='graph')window.openGraphing();if(action==='history')window.showEquationHistory();if(action==='test-voice')window.speak('This is your selected Kokoro voice.')});document.querySelector('#theme-select').onchange=event=>document.body.dataset.theme=event.target.value;document.querySelector('#size-range').oninput=event=>document.documentElement.style.setProperty('--font',event.target.value+'px');if(speech)speech.onvoiceschanged=loadVoices;makeButtons();loadVoices();
