/* Speech, display, calculator evaluation, dynamic boards, and tab navigation. */
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {});
const display=document.querySelector('#display');const status=document.querySelector('#status');const speech=window.speechSynthesis;let voices=[];let lastResult='';
const phrases=['I need help','I have a question',"I'm ready", "I don't understand",'Can you repeat that?','I need more time','Thank you'];
const sets={algebra:[['x','x'],['y','y'],['a','a'],['b','b'],['=',' = '],['≠',' != '],['<',' < '],['>',' > '],['^','**'],['|x|','abs(']],calculus:[['∫','Integral: '],['d/dx','Derivative: '],['lim','Limit: '],['Σ','Sum: '],['A','Area: '],['dx',' dx '],['dy',' dy '],['∞','∞']],greek:[['α','α'],['β','β'],['γ','γ'],['δ','δ'],['θ','θ'],['λ','λ'],['μ','μ'],['σ','σ'],['φ','φ'],['ω','ω'],['∧','∧'],['∨','∨'],['∩','∩'],['∪','∪'],['→','→'],['∀','∀'],['∃','∃'],['∈','∈']],functions:[['sin','sin('],['cos','cos('],['tan','tan('],['√','sqrt('],['ln','log('],['log₁₀','log10('],['eˣ','exp('],['!','factorial('],['⌈x⌉','ceil('],['⌊x⌋','floor('],['|x|','abs('],['sin⁻¹','asin('],['cos⁻¹','acos('],['tan⁻¹','atan(']],words:[['I','I'],['need','need'],['want','want'],['like','like'],['feel','feel'],['more','more'],['less','less'],['to','to'],['go','go'],['stop','stop'],['because','because'],['today','today']]};
function setStatus(message){status.textContent=message}function append(value,space=false){if(!space&&window.insertFunctionValue?.(value))return;display.value+=(space&&display.value?' ':'')+value;display.focus()}function speak(text=display.value){if(!text.trim())return;const utterance=new SpeechSynthesisUtterance(text);const selected=document.querySelector('#voice-select').value;const voice=voices.find(item=>item.name===selected);if(voice)utterance.voice=voice;utterance.rate=Number(document.querySelector('#rate-range').value)/175;utterance.volume=Number(document.querySelector('#volume-range').value)/100;speech.cancel();speech.speak(utterance);setStatus('Speaking current display.')}
function makeButtons(){const quick=document.querySelector('#quick-phrases');phrases.forEach(text=>{const button=document.createElement('button');button.className='button';button.textContent=text;button.onclick=()=>{display.value=text;setStatus('Speaking phrase with Kokoro: '+text);window.speak(text)};quick.append(button)});document.querySelectorAll('[data-buttons]').forEach(container=>{sets[container.dataset.buttons].forEach(([label,value])=>{const button=document.createElement('button');button.className='button';button.textContent=label;button.onclick=()=>append(value,container.dataset.buttons==='words');container.append(button)})})}

function loadVoices(){voices=speech.getVoices();const select=document.querySelector('#voice-select');select.innerHTML='';voices.forEach(voice=>{const option=document.createElement('option');option.value=voice.name;option.textContent=voice.name;select.append(option)});const preferred=voices.find(v=>/zira|aria|jenny|samantha|hazel/i.test(v.name));if(preferred)select.value=preferred.name}function selectTab(tab){document.querySelectorAll('.main-tabs .tab').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));document.querySelectorAll('.subject').forEach(section=>section.classList.toggle('active',section.id===tab))}function selectSubtab(button){const parent=button.closest('.subject');parent.querySelectorAll('.subtab').forEach(item=>item.classList.toggle('active',item===button));const target=button.dataset.subtab;parent.querySelectorAll('.subpanel').forEach(panel=>panel.classList.toggle('active',panel.id===target))}
document.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.tab){selectTab(target.dataset.tab);return}if(target.dataset.subtab){selectSubtab(target);return}if(target.dataset.value){append(target.dataset.value);return}const action=target.dataset.action;if(action==='speak')window.speak();if(action==='backspace'&&!window.backspaceMath?.())display.value=display.value.slice(0,-1);if(action==='clear')display.value='';if(action==='evaluate')window.evaluate();if(action==='graph')setStatus('Graphing workspace selected. Enter an expression in the Math Board first.');if(action==='history')setStatus(lastResult?'Last result: '+lastResult:'Equation history is empty.');if(action==='test-voice')window.speak('This is your selected Kokoro voice.')});document.querySelector('#theme-select').onchange=event=>document.body.dataset.theme=event.target.value;document.querySelector('#size-range').oninput=event=>document.documentElement.style.setProperty('--font',event.target.value+'px');speech.onvoiceschanged=loadVoices;makeButtons();loadVoices();
